PGS/WebApplication1/WebApplication1/Entities/Game.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebApplication1.Entities
{
    public class Game
    {
        [Key]
        public int Id { get; set; }
        [MinLength(5)]
        public string Name { get; set; }
        [Range(0.0, float.MaxValue)]
        public float Price { get; set; }
    }
}

PGS/WebApplication1/WebApplication1/Controllers/TisuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class TisuController : Controller
    {
        readonly ApplicationDbContext m_db = ApplicationDbContext.Create();

        // GET: Tisu
        public ActionResult Index()
        {
            return View("Game");
        }
        public ActionResult Game()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Game(TisuModel a_model)
        {
            
            if (!ModelState.IsValid)
            {
                return View(a_model);
            }
            m_db.m_game_db.Add(new Entities.Game() { Name = a_model.Name, Price = a_model.Price });
            m_db.SaveChanges();
            return View(a_model);
        }
    }
}

PGS/WebApplication1/WebApplication1/Views/Tisu/Game.cshtml
@model WebApplication1.Models.TisuModel
@{
    ViewBag.Title = "Game";
}
@using (Html.BeginForm("Game", "Tisu", FormMethod.Post))
{

    <div class="form-group">
        <label for="example">Name</label>
        @*<input type="Name" class="form-control" id="example" placeholder="Name"/>*@
         @Html.TextBoxFor(model => model.Name,new { @class = "form-control", @placeholder="Name"})
       @* @Html.ValidationMessageFor(model =>model.Name,)*@
    </div>
    <div>
        @Html.EditorFor(model => model.Price)
    </div>
    <input type="submit" value="Send" />
}
<h2>Game</h2>