Notatki.Warsztat-master/Notatki.PWR/Controllers/NoteController.cs
using System.Linq;
using System.Web.Mvc;
using Notatki.PWR.Models;

namespace Notatki.PWR.Controllers
{
    public class NoteController : Controller
    {
        // GET: Note
        public ActionResult Index()
        {
            ViewBag.Success = TempData["Success"];
            return View();
        }

        [HttpPost]
        public ActionResult Index(AddNoteModel model)
        {
            if (ModelState.IsValid)
            {
                var note = new Note();
                note.Title = model.Title;
                note.Content = model.Content;
                using (var ctx = new ApplicationDbContext())
                {
                    ctx.Notes.Add(note);
                    ctx.SaveChanges();
                }
                TempData["Success"] = "Notatka została zapisana!";
                return RedirectToAction("Index");
            }
            ViewBag.Error = "Wypełnij poprawnie pola notatki.";
            return View(model);
        }

        public ActionResult List()
        {
            var viewmodel = new ListNotesViewModel();

            using (var ctx = new ApplicationDbContext())
            {
                var notes = ctx.Notes.Select(note => new ListNoteItem()
                {
                    Title = note.Title,
                    Id = note.Id.ToString()
                }).ToList();

                viewmodel.Notes = notes;
            }
            return View(viewmodel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            using (var ctx=new ApplicationDbContext())
            {
                var note = ctx.Notes.Single(n => n.Id == id);
                ctx.Notes.Remove(note);
                ctx.SaveChanges();
            }
            return RedirectToAction("List");
        }

        public ActionResult Edit(int id)
        {
            var viewmodel = new EditViewModel();
            using (var ctx=new ApplicationDbContext())
            {
                var note = ctx.Notes.Single(n => n.Id == id);
                viewmodel.Title = note.Title;
                viewmodel.Content = note.Content;
                viewmodel.Id = note.Id;
            }
            return View(viewmodel);
        }

        [HttpPost]
        public ActionResult Edit(EditNoteDto model)
        {
            if (ModelState.IsValid)
            {
                using (var ctx=new ApplicationDbContext())
                {
                    var note = ctx.Notes.Single(n => n.Id == model.Id);
                    note.Title = model.Title;
                    note.Content = model.Content;
                    ctx.SaveChanges();
                }
                return RedirectToAction("List");
            }
            return View(new EditViewModel()
            {
                Id = model.Id,
                Title = model.Title,
                Content = model.Content
            });
        }
    }
    

    public class EditNoteDto
    {
        public int Id { get; set; }

        public string Title { get; set; }

        public string Content { get; set; }
    }

    public class EditViewModel
    {
        public int Id { get; set; }

        public string Title { get; set; }

        public string Content { get; set; }
    }
}

Notatki.Warsztat-master/Notatki.PWR/Views/Note/Edit.cshtml
@model Notatki.PWR.Controllers.EditViewModel

@{
    ViewBag.Title = "title";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edytuj notatkę</h2>
<form method="post">
    <div class="form-group">
        <label for="title">Tytuł:</label>
        @Html.TextBoxFor(m => m.Title, new { @class = "form-control", placeholder = "Podaj tytuł notatki" })
    </div>

    <div class="form-group">
        <label for="content">Podaj treść notatki:</label>
        @Html.TextAreaFor(m => m.Content, new { @class = "form-control" })
    </div>
    @Html.HiddenFor(m=>m.Id)
    <button type="submit" class="btn btn-default">Zapisz</button>
</form>

Notatki.Warsztat-master/Notatki.PWR/Views/Note/Index.cshtml
@model Notatki.PWR.Models.AddNoteModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (@ViewBag.Error != null)
{
    <div class="alert alert-danger">@ViewBag.Error</div>
}
@if (@ViewBag.Success != null)
{
    <div class="alert alert-success">@ViewBag.Success</div>
}
<h1>Dodaj notatkę</h1>
<form method="post">
    <div class="form-group">
        <label for="title">Tytuł:</label>
        @Html.TextBoxFor(m => m.Title, new { @class = "form-control", placeholder = "Podaj tytuł notatki" })
    </div>

    <div class="form-group">
        <label for="content">Podaj treść notatki:</label>
        @Html.TextAreaFor(m => m.Content, new { @class = "form-control" })
    </div>

    <button type="submit" class="btn btn-default">Zapisz</button>
</form>

Notatki.Warsztat-master/Notatki.PWR/Views/Note/List.cshtml
@model Notatki.PWR.Models.ListNotesViewModel

@{
    ViewBag.Title = "title";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Lista Notatek</h2>
<table class="table table-hover table-striped">
    <thead>
    <tr>
        <th>Id</th>
        <th>Tytuł</th>
        <th>Akcja</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var note in Model.Notes)
    {
        <tr>
            <td>@note.Id</td>
            <td>@note.Title</td>
            <td>
                @using (Html.BeginForm("Delete","Note",FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <input name="id" value="@note.Id" type="hidden"/>
                    <button class="btn btn-danger" type="submit">
                        <span class="glyphicon glyphicon-trash"></span>Usuń
                    </button>
                }
                <a class="btn btn-default" href="@Url.Action("Edit",new { id = note.Id })">
                    <span class="glyphicon glyphicon-edit"></span>Popraw
                </a>
            </td>
        </tr>
    }
    </tbody>
</table>